// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwcKpDjHAfidFVRKP9EHgv4OG4n_Ih9M',
    appId: '1:30761013126:web:9f70eee7d330056fa6a607',
    messagingSenderId: '30761013126',
    projectId: 'yapper-01',
    authDomain: 'yapper-01.firebaseapp.com',
    storageBucket: 'yapper-01.firebasestorage.app',
    measurementId: 'G-B395XG8GTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1A7QyjV3U_nNFmKO8y-8AVQF6K-qFhks',
    appId: '1:30761013126:android:c249a84a09df9271a6a607',
    messagingSenderId: '30761013126',
    projectId: 'yapper-01',
    storageBucket: 'yapper-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOo3EUTc7wY7eXayruos6E-S9HsLLAshY',
    appId: '1:30761013126:ios:5c6595b93920b073a6a607',
    messagingSenderId: '30761013126',
    projectId: 'yapper-01',
    storageBucket: 'yapper-01.firebasestorage.app',
    iosClientId: '30761013126-t1b0eija9djoqph4vbdjuuf2ubfqdhs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOo3EUTc7wY7eXayruos6E-S9HsLLAshY',
    appId: '1:30761013126:ios:5c6595b93920b073a6a607',
    messagingSenderId: '30761013126',
    projectId: 'yapper-01',
    storageBucket: 'yapper-01.firebasestorage.app',
    iosClientId: '30761013126-t1b0eija9djoqph4vbdjuuf2ubfqdhs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJwcKpDjHAfidFVRKP9EHgv4OG4n_Ih9M',
    appId: '1:30761013126:web:407d9c679315737ba6a607',
    messagingSenderId: '30761013126',
    projectId: 'yapper-01',
    authDomain: 'yapper-01.firebaseapp.com',
    storageBucket: 'yapper-01.firebasestorage.app',
    measurementId: 'G-VMH1PKCYXC',
  );
}
